server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.73.3
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    path: C:/tmp/sms/sms.txt